import './registerPlugins.js'; // must run before any model compiles
export { User } from './User.js';
export { Organization } from './Organization.js';
export { Module } from './Module.js';
export { Batch } from './Batch.js';
export { ClassSchedule } from './ClassSchedule.js';
export { ClassJoin } from './ClassJoin.js';
export { ClassRating } from './ClassRating.js';
export { Attendance } from './Attendance.js';
export { Assessment } from './Assessment.js';
export { QuestionBankItem } from './QuestionBank.js';
export { SyllabusImportRequest } from './SyllabusImportRequest.js';
export { Submission } from './Submission.js';
export { Resource } from './Resource.js';
export { Certificate } from './Certificate.js';
export { CertificateTemplate } from './CertificateTemplate.js';
export { ExternalCertificate } from './ExternalCertificate.js';
export { Project } from './Project.js';
export { ModuleProgress } from './ModuleProgress.js';
export { Settings, getSettings, getStoredAiApiKey, getStoredZoomCreds, getStoredSebConfigKey } from './Settings.js';
export { Doubt } from './Doubt.js';
export { Announcement } from './Announcement.js';
export { Notification } from './Notification.js';
export { AuditLog } from './AuditLog.js';
